package io.github.dftrakesh.roadrunner.models;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.2
 * 2022-09-05T10:04:47.080+05:30
 * Generated source version: 3.5.2
 *
 */
@WebService(targetNamespace = "https://webservices.rrts.com/ratequote/", name = "RateQuoteSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface RateQuoteSoap {

    /**
     * This method sends back a rate quote from the Road Runner Transportation Services System
     */
    @WebMethod(operationName = "RateQuote", action = "https://webservices.rrts.com/ratequote/RateQuote")
    @RequestWrapper(localName = "RateQuote", targetNamespace = "https://webservices.rrts.com/ratequote/", className = "com.taim.api.rrts.RateQuote")
    @ResponseWrapper(localName = "RateQuoteResponse", targetNamespace = "https://webservices.rrts.com/ratequote/", className = "com.taim.api.rrts.RateQuoteResponse")
    @WebResult(name = "RateQuoteResult", targetNamespace = "https://webservices.rrts.com/ratequote/")
    public QuoteResponse rateQuote(

        @WebParam(name = "request", targetNamespace = "https://webservices.rrts.com/ratequote/")
            QuoteRequest request,
        @WebParam(name = "AuthenticationHeader", targetNamespace = "https://webservices.rrts.com/ratequote/", header = true)
            AuthenticationHeader authenticationHeader
    );

    /**
     * This method sends back a rate quote from the Road Runner Transportation Services System
     */
    @WebMethod(operationName = "RateQuoteByAccount", action = "https://webservices.rrts.com/ratequote/RateQuoteByAccount")
    @RequestWrapper(localName = "RateQuoteByAccount", targetNamespace = "https://webservices.rrts.com/ratequote/", className = "com.taim.api.rrts.RateQuoteByAccount")
    @ResponseWrapper(localName = "RateQuoteByAccountResponse", targetNamespace = "https://webservices.rrts.com/ratequote/", className = "com.taim.api.rrts.RateQuoteByAccountResponse")
    @WebResult(name = "RateQuoteByAccountResult", targetNamespace = "https://webservices.rrts.com/ratequote/")
    public QuoteResponse rateQuoteByAccount(

        @WebParam(name = "request", targetNamespace = "https://webservices.rrts.com/ratequote/")
            QuoteAccountRequest request,
        @WebParam(name = "AuthenticationHeader", targetNamespace = "https://webservices.rrts.com/ratequote/", header = true)
        AuthenticationHeader authenticationHeader
    );

    /**
     * This method sends back a rate quote from the Road Runner Transportation Services System
     */
    @WebMethod(operationName = "RateQuoteByAccountByTerminal", action = "https://webservices.rrts.com/ratequote/RateQuoteByAccountByTerminal")
    @RequestWrapper(localName = "RateQuoteByAccountByTerminal", targetNamespace = "https://webservices.rrts.com/ratequote/", className = "com.taim.api.rrts.RateQuoteByAccountByTerminal")
    @ResponseWrapper(localName = "RateQuoteByAccountByTerminalResponse", targetNamespace = "https://webservices.rrts.com/ratequote/", className = "com.taim.api.rrts.RateQuoteByAccountByTerminalResponse")
    @WebResult(name = "RateQuoteByAccountByTerminalResult", targetNamespace = "https://webservices.rrts.com/ratequote/")
    public QuoteResponse rateQuoteByAccountByTerminal(

        @WebParam(name = "request", targetNamespace = "https://webservices.rrts.com/ratequote/")
            QuoteAccountByTerminalRequest request,
        @WebParam(name = "AuthenticationHeader", targetNamespace = "https://webservices.rrts.com/ratequote/", header = true)
        AuthenticationHeader authenticationHeader
    );
}
