
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package io.github.dftrakesh.roadrunner.models;

import lombok.SneakyThrows;
import lombok.extern.log4j.Log4j2;
import org.springframework.stereotype.Service;

import javax.jws.WebService;

/**
 * This class was generated by Apache CXF 3.5.2
 * 2022-09-05T10:04:47.071+05:30
 * Generated source version: 3.5.2
 */

@WebService(
    serviceName = "RateQuote",
    portName = "RateQuoteSoap",
    targetNamespace = "https://webservices.rrts.com/ratequote/",
    wsdlLocation = "https://webservices.rrts.com/rating/ratequote.asmx?wsdl",
    endpointInterface = "com.taim.api.rrts.RateQuoteSoap")

@Service
public class RateQuoteSoapImpl implements RateQuoteSoap {

    /* (non-Javadoc)
     * @see com.taim.api.rrts.RateQuoteSoap#rateQuote(com.taim.api.rrts.QuoteRequest request, com.taim.api.rrts.AuthenticationHeader authenticationHeader)*
     */
    @SneakyThrows
    public QuoteResponse rateQuote(QuoteRequest request, AuthenticationHeader authenticationHeader) {

//        try {
            QuoteResponse _return = null;
            RateQuote_Service rateQuote_service = new RateQuote_Service();
            RateQuoteSoap rateQuoteSoap12 = rateQuote_service.getRateQuoteSoap12();
            _return = rateQuoteSoap12.rateQuote(request, authenticationHeader);
            return _return;
//        } catch (Exception exception) {
//            log.error("Exception occurred while calling road runner rate quote api: {}", exception.getMessage(), exception);
//            exception.printStackTrace();
//            throw new RuntimeException(exception);
//        }
    }

    /* (non-Javadoc)
     * @see com.taim.api.rrts.RateQuoteSoap#rateQuoteByAccount(com.taim.api.rrts.QuoteAccountRequest request, com.taim.api.rrts.AuthenticationHeader authenticationHeader)*
     */
    @SneakyThrows
    public QuoteResponse rateQuoteByAccount(QuoteAccountRequest request, AuthenticationHeader authenticationHeader) {
//        try {
            QuoteResponse _return = null;
            return _return;
//        } catch (Exception exception) {
//            exception.printStackTrace();
//            throw new RuntimeException(exception);
//        }
    }

    /* (non-Javadoc)
     * @see com.taim.api.rrts.RateQuoteSoap#rateQuoteByAccountByTerminal(com.taim.api.rrts.QuoteAccountByTerminalRequest request, com.taim.api.rrts.AuthenticationHeader authenticationHeader)*
     */
    @SneakyThrows
    public QuoteResponse rateQuoteByAccountByTerminal(QuoteAccountByTerminalRequest request, AuthenticationHeader authenticationHeader) {
//        try {
            QuoteResponse _return = null;
            return _return;
//        } catch (Exception exception) {
//            exception.printStackTrace();
//            throw new RuntimeException(exception);
//        }
    }

}
