
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package io.github.dftrakesh.roadrunner.models;

import lombok.SneakyThrows;
import org.springframework.stereotype.Service;

import javax.jws.WebService;

/**
 * This class was generated by Apache CXF 3.5.2
 * 2022-09-05T10:04:47.016+05:30
 * Generated source version: 3.5.2
 */

@WebService(
    serviceName = "RateQuote",
    portName = "RateQuoteSoap12",
    targetNamespace = "https://webservices.rrts.com/ratequote/",
    wsdlLocation = "https://webservices.rrts.com/rating/ratequote.asmx?wsdl",
    endpointInterface = "com.taim.api.rrts.RateQuoteSoap")
@Service
public class RateQuoteSoap12Impl implements RateQuoteSoap {

    /* (non-Javadoc)
     * @see com.taim.api.rrts.RateQuoteSoap#rateQuote(com.taim.api.rrts.QuoteRequest request, com.taim.api.rrts.AuthenticationHeader authenticationHeader)*
     */
    @SneakyThrows
    public QuoteResponse rateQuote(QuoteRequest request, AuthenticationHeader authenticationHeader) {

        QuoteResponse _return = null;
        return _return;
    }

    /* (non-Javadoc)
     * @see com.taim.api.rrts.RateQuoteSoap#rateQuoteByAccount(com.taim.api.rrts.QuoteAccountRequest request, com.taim.api.rrts.AuthenticationHeader authenticationHeader)*
     */
    @SneakyThrows
    public QuoteResponse rateQuoteByAccount(QuoteAccountRequest request, AuthenticationHeader authenticationHeader) {

        QuoteResponse _return = null;
        return _return;
    }

    /* (non-Javadoc)
     * @see com.taim.api.rrts.RateQuoteSoap#rateQuoteByAccountByTerminal(com.taim.api.rrts.QuoteAccountByTerminalRequest request, com.taim.api.rrts.AuthenticationHeader authenticationHeader)*
     */
    @SneakyThrows
    public QuoteResponse rateQuoteByAccountByTerminal(QuoteAccountByTerminalRequest request, AuthenticationHeader authenticationHeader) {

        QuoteResponse _return = null;
        return _return;
    }

}
