package io.github.dftrakesh.roadrunner.models;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.5.2
 * 2022-09-05T10:04:47.085+05:30
 * Generated source version: 3.5.2
 *
 */
@WebServiceClient(name = "RateQuote",
                  wsdlLocation = "https://webservices.rrts.com/rating/ratequote.asmx?wsdl",
                  targetNamespace = "https://webservices.rrts.com/ratequote/")
public class RateQuote_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("https://webservices.rrts.com/ratequote/", "RateQuote");
    public final static QName RateQuoteSoap12 = new QName("https://webservices.rrts.com/ratequote/", "RateQuoteSoap12");
    public final static QName RateQuoteSoap = new QName("https://webservices.rrts.com/ratequote/", "RateQuoteSoap");
    static {
        URL url = null;
        try {
            url = new URL("https://webservices.rrts.com/rating/ratequote.asmx?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RateQuote_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "https://webservices.rrts.com/rating/ratequote.asmx?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RateQuote_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RateQuote_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RateQuote_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public RateQuote_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public RateQuote_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public RateQuote_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns RateQuoteSoap
     */
    @WebEndpoint(name = "RateQuoteSoap12")
    public io.github.dftrakesh.roadrunner.models.RateQuoteSoap getRateQuoteSoap12() {
        return super.getPort(RateQuoteSoap12, io.github.dftrakesh.roadrunner.models.RateQuoteSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RateQuoteSoap
     */
    @WebEndpoint(name = "RateQuoteSoap12")
    public RateQuoteSoap getRateQuoteSoap12(WebServiceFeature... features) {
        return super.getPort(RateQuoteSoap12, RateQuoteSoap.class, features);
    }


    /**
     *
     * @return
     *     returns RateQuoteSoap
     */
    @WebEndpoint(name = "RateQuoteSoap")
    public RateQuoteSoap getRateQuoteSoap() {
        return super.getPort(RateQuoteSoap, RateQuoteSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RateQuoteSoap
     */
    @WebEndpoint(name = "RateQuoteSoap")
    public RateQuoteSoap getRateQuoteSoap(WebServiceFeature... features) {
        return super.getPort(RateQuoteSoap, RateQuoteSoap.class, features);
    }

}
